fresh: ## Fresh databases
	php artisan migrate:fresh --seed
	php artisan migrate:fresh --database=mysql_test

refresh: ## Refresh databases
	php artisan migrate:refresh --seed
	php artisan migrate:refresh --database=mysql_test

test: ## Run test suit
	./vendor/bin/phpcs
	./vendor/bin/phpstan --memory-limit=-1
	./vendor/bin/phpunit

cs: ## Run phpcs
	bin/phpcs

csfix: ## Autofix phpcs errors
	./vendor/bin/phpcbf

stan: ## Run phpstan
	./vendor/bin/phpstan --memory-limit=-1

unit:
	./vendor/bin/phpunit
